name: Azure ML CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'orchestration/**'
      - 'pipelines/**'
      - 'customers/**'
      - 'config/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: 2a7e07b9-7b60-42ae-a7d3-9293dfb0d060

      - name: Install ML extension
        run: |
          az extension add -n ml -y || az extension update -n ml

      - name: Deploy Orchestrator
        run: |
          az ml job create --file orchestration/orch_job.yaml \
            --resource-group d-ci-logistics_group \
            --workspace-name shippingml

      - name: Deploy Customer Pipelines
        run: |
          for c in tata hyundai volkswagen bmw; do
            az ml job create \
              --file pipelines/$c/pipeline.yaml \
              --resource-group d-ci-logistics_group \
              --workspace-name shippingml
          done
