name: Deploy Orchestration Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Azure ML extension
      run: |
        az extension add -n ml --yes
        az --version

    - name: Azure Login using Federated Identity
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREML_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Orchestration Pipeline
      run: |
        az ml job create \
        --file orchestration/orch_job.yaml \
        --resource-group d-ci-logistics_group \
        --workspace-name shippingml
