name: Deploy Orchestration Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write      # IMPORTANT
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login using Federated Identity
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: false
        enable-AzPSSession: false

    - name: Install Azure ML extension
      run: |
        az extension add -n ml -y
        az version

    - name: Debug current directory
      run: |
        echo "Listing repo files..."
        ls -R .

    - name: Deploy Orchestration Pipeline
      run: |
        az ml job create \
          --file orchestration/orch_job.yaml \
          --resource-group d-ci-logistics_group \
          --workspace-name shippingml
